### PR TITLE
Merge flutter_math_fork (containing Flutter 2.0 compatibility changes)

### PR DESCRIPTION
**Pull request by creativecreatorormaybenot**
As `flutter_math` has not been maintained for the past few months, we decided to **fork it** into [flutter_math_fork](https://github.com/simpleclub-extended/flutter_math_fork) in order to publish it as a compatible Pub package.

The Pub dependency is the following:

```yaml
flutter_math_fork: ^3.0.0
```

---

We do not intend to maintain this fork in the long-term. Instead, we would like to merge this effort back into the original repo, which is why this branch will be kept in sync.

### CODE REVIEW

**Comment by Skyost** [comment]
Great initiative !

**Comment by walsha2** [comment]
@creativecreatorormaybenot - thanks for the information. I have a question about long term though and maybe you might have some insight from a `CaTeX` perspective.

Initially I was much more drawn to `CaTeX` because it seemed to be developed by a team and not an individual. I am always hesitant to use packages with only one maintainer because of issues like this. On the `CaTeX` page it states:

> We worked together with flutter_math to make that package have all the necessary functionality and you should be able to use it in place of CaTeX for the while being.

Is this still the stance? We, the community, really do need a well maintained Flutter TeX effort. I would be more than happy to support but I have no idea where those efforts are being centralized. `flutter_math`? `CaTeX`? `flutter_math_fork`?

Any insight would be appreciated!

**Comment by creativecreatorormaybenot** [comment]
@walsha2 Hi, glad you are interested :)

I understand your concerns and I agree with you that we need something like KaTeX (well maintained) in Flutter - that was the idea with CaTeX.

To be frank, we did not have the resources to develop CaTeX at the time and @znjameswu did such an amazing job on `flutter_math` afterwards that we figured we would go with it. 

The vision is definitely still to make CaTeX a reality (beyond prototype status) and I think there is a lot to be learned from `flutter_math`. Additionally, we are planning to expand on the ecosystem, which you will be seeing *very soon* (I guess you can follow me if you are curious 😄). It will be clear that it would make sense for simpleclub to dive deeper into the topic, but it really depends on the path of the simpleclub product. 

If you would like to collaborate, let me know :)

**Comment by creativecreatorormaybenot** [comment]
I am closing this PR for now as the `flutter_math` repo is not being maintained.

**Pull request closed without merging**
