### PR TITLE
Closes #37 Hot fix for Flutter 2.0 stable version

### LINKED ISSUE #37: /flutter_math-0.2.1/lib/src/widgets/selection/overlay.dart:302:46: Error: Too few positional arguments: 8 required, 7 given.         child: selectionControls.buildToolbar(                                              ^
I'm getting this on compile.  

This is my environment definition:

environment:
  sdk: ">=2.12.0-0 <3.0.0"

What am I doing wrong?

### PR DESCRIPTION
**Pull request by walsha2**
@znjameswu this resolves #37 to fix the currently broken version of this package on the latest Flutter stable. Can you please review and accept pull request.

### CODE REVIEW

**Comment by beingentangled** [comment]
is this working?

**Comment by walsha2** [comment]
> is this working?

@beingentangled I have tried to contact @znjameswu but still have not heard back. We need someone with write access to the repo to merge this in. The pull request should resolve the build error, yes.

I was initially using `CaTeX` and then they posted:

> We worked together with flutter_math to make that package have all the necessary functionality and you should be able to use it in place of CaTeX for the while being.

So for that reason, I switched to `flutter_math` thinking it would be actively maintained. We need some more maintainers. @znjameswu please consider giving other users write privileges to help with the development load. Since  `CaTeX` is not going to be actively maintained, this is an important package that needs to be up to date with latest dart/flutter changes. 

We don't need yet another TeX fork for flutter use so it would be nice with the community coalesced on a single package. Pub.dev packages are already very fragmented and there is lots of duplicate work.

**Comment by beingentangled** [comment]
@walsha2 Hope, I can use your repo for getting the fix until this request is merged.

**Comment by beingentangled** [comment]
@walsha2 after using your version for the fix I'm getting the following error:
Because every version of flutter_math from git depends on provider ^5.0.0-nullsafety.2 and *** depends on provider ^4.3.2+2, flutter_math from git is forbidden.
So, because *** depends on flutter_math from git, version solving failed.
pub get failed (1; So, because *** depends on flutter_math from git, version solving failed.)

**Comment by walsha2** [comment]
@beingentangled If you need the null-safety version you should probably use the following repo as discussed by @creativecreatorormaybenot 

https://github.com/simpleclub-extended/flutter_math_fork

If you need the non null-safety version which resolves the dependency issue you see above, you will need the following:

```
  flutter_math:
    git:
      url: git://github.com/walsha2/flutter_math
      ref: 37-flutter-2-hot-fix-0.2.x
```

**Comment by walsha2** [comment]
Closing this PR in favor of https://github.com/simpleclub-extended/flutter_math_fork for the null-safety version

**Pull request closed without merging**
